### ISSUE TITLE
Role is not idempotent

### ISSUE THREAD

**Issue by spatterIight** [mother-of-all-self-hosting/ansible-role-traefik#5]
When running this role there are 2 tasks that are marked as changed everytime:

![Image](https://github.com/user-attachments/assets/50ef92fd-f81f-427c-8073-4442af9fb070)

The relevant code is:

```yaml
- name: Ensure Traefik environment variables installed
  ansible.builtin.copy:
    content: "{{ traefik_environment_variables }}"
    dest: "{{ traefik_config_dir_path }}/env"
    owner: "{{ traefik_uid }}"
    group: "{{ traefik_gid }}"
    mode: 0640

- name: Ensure Traefik support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ traefik_config_dir_path }}/{{ item }}"
    owner: "{{ traefik_uid }}"
    group: "{{ traefik_gid }}"
    mode: 0640
  with_items:
    - env
    - labels
```

It looks like the issue is due to the `env` file being applied twice. The first time (for me) it is blank, then the second time has my actual environment variables from `traefik_environment_variables_additional_variables`

This happening because there are two variables which control environment variables:

1. `traefik_environment_variables`
2. `traefik_environment_variables_additional_variables`

It looks like the 2nd variable was added by mistake when DNS ACME support was added? (not 100% sure on this)

To resolve this I believe `traefik_environment_variables_additional_variables`  should be marked as deprecated via `tasks/validate_config.yml`. It should instruct the user to instead use `traefik_environment_variables`. Additionally, the `Ensure Traefik environment variables installed` task should be removed and the templated `env` file should template `traefik_environment_variables` instead of `traefik_environment_variables_additional_variables`

I will make a PR for this
